// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT47YuEtk47DjSJs1bBr9K_74wGF-ggpk',
    appId: '1:571310969236:web:6c067c1d55ddb8308d3f81',
    messagingSenderId: '571310969236',
    projectId: 'springapi-a2648',
    authDomain: 'springapi-a2648.firebaseapp.com',
    storageBucket: 'springapi-a2648.appspot.com',
    measurementId: 'G-S27NTS98LT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-uKgoBrPlfHnwbSJZWQDwA4qEJFqPSQ',
    appId: '1:571310969236:ios:d36abc26c3a1955b8d3f81',
    messagingSenderId: '571310969236',
    projectId: 'springapi-a2648',
    storageBucket: 'springapi-a2648.appspot.com',
    iosBundleId: 'com.example.mcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-uKgoBrPlfHnwbSJZWQDwA4qEJFqPSQ',
    appId: '1:571310969236:ios:d36abc26c3a1955b8d3f81',
    messagingSenderId: '571310969236',
    projectId: 'springapi-a2648',
    storageBucket: 'springapi-a2648.appspot.com',
    iosBundleId: 'com.example.mcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArPkwk97wxnsVhPGFso5BY-JTlMZY-QeQ',
    appId: '1:571310969236:web:9f1bf8e9d88379da8d3f81',
    messagingSenderId: '571310969236',
    projectId: 'springapi-a2648',
    authDomain: 'springapi-a2648.firebaseapp.com',
    storageBucket: 'springapi-a2648.appspot.com',
    measurementId: 'G-WE5GT14DL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuYv47Xoa6BhHoertIujUps4ox4RyPoWk',
    appId: '1:571310969236:android:d6312bf8cff8f6738d3f81',
    messagingSenderId: '571310969236',
    projectId: 'springapi-a2648',
    storageBucket: 'springapi-a2648.appspot.com',
  );

}